pg_replication:
  query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))::INT as lag"
  metrics:
    - lag:
        usage: "GAUGE"
        description: "Replication lag behind master in seconds"

pg_stat_activity:
  query: "SELECT datname, count(*) as count FROM pg_stat_activity GROUP BY datname"
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - count:
        usage: "GAUGE"
        description: "Number of connections"

pg_database_size:
  query: "SELECT datname, pg_database_size(datname) as size FROM pg_database"
  metrics:
    - datname:
        usage: "LABEL"
        description: "Name of the database"
    - size:
        usage: "GAUGE"
        description: "Disk space used by the database"
